time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "HRRR_15min"
InputForcings: [6,26] 
InputForcingDirectories: ['/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/HRRR_15min/RAP',"/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/HRRR_15min/HRRR"]
InputForcingTypes: ["GRIB2","GRIB2"]
InputMandatory: [1,1]
OutputFrequency: 15
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/Short_range"
Output: 1
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : -9999
RefcstBDateProc: "202407121300"
ForecastFrequency: 60
ForecastShift: 0
ForecastInputHorizons: [720,720]
ForecastInputOffsets: [0,0]
GeogridIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/geo_em_CONUS.nc"
SpatialMetaIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/GEOGRID_LDASOUT_Spatial_Metadata_CONUS.nc"
GRID_TYPE: "gridded"
LONVAR: 'XLONG_M'
LATVAR: 'XLAT_M'
HGTVAR: 'Element_Elevation'
SINALPHA: 'SINALPHA'
COSALPHA: 'COSALPHA'
HGTVAR: 'HGT_M'
IgnoredBorderWidths: [0,0]
RegridOpt: [1,1]
ForcingTemporalInterpolation: [0,0]
TemperatureBiasCorrection: [0,0]
PressureBiasCorrection: [0,0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [0,0]
SwBiasCorrection: [0,0]
LwBiasCorrection: [0,0]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [0,0]
ShortwaveDownscaling: [0,0]
PressureDownscaling: [0,0]
PrecipDownscaling: [0,0]
HumidityDownscaling: [0,0]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Medium_Range","./NWM_Params"]
SuppPcp: []
SuppPcpForcingTypes: ''
SuppPcpDirectories: ''
SuppPcpParamDir: ''
RegridOptSuppPcp: []
SuppPcpTemporalInterpolation: []
SuppPcpInputOffsets: []
SuppPcpMandatory: []
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFrac: 1
