# GitLab CI/CD configuration file for ngen-forcing repository
include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - build
  - unit_test
  - sonarqube
  - test
  - deploy

image: registry.sh.nextgenwaterprediction.com/infrastructure/docker/docker:latest

variables:
    DOCKER_IMAGE_NAME_BMI_FORCING: $CI_REGISTRY_IMAGE/ngen-bmi-forcing
    DOCKER_IMAGE_NAME_LUMPED_FORCING: $CI_REGISTRY_IMAGE/ngen-lumped-forcing
    DOCKER_IMAGE_NAME_COASTAL: $CI_REGISTRY_IMAGE/ngen-coastal
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - echo "Logging in to Gitlab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Building ${CI_PROJECT_NAME} docker images.. "
    - docker build --file=Dockerfile.bmi-forcings --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} --tag "$DOCKER_IMAGE_NAME_BMI_FORCING:$DOCKER_IMAGE_TAG" .
    - docker push $DOCKER_IMAGE_NAME_BMI_FORCING:$DOCKER_IMAGE_TAG
    - docker build --file=Dockerfile.lumped-forcings --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} --tag "$DOCKER_IMAGE_NAME_LUMPED_FORCING:$DOCKER_IMAGE_TAG" .
    - docker push $DOCKER_IMAGE_NAME_LUMPED_FORCING:$DOCKER_IMAGE_TAG
    - docker build --secret id=GITLAB_TOKEN,env=GITLAB_TOKEN --file=Dockerfile.ngencoastal --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} --tag "$DOCKER_IMAGE_NAME_COASTAL:$DOCKER_IMAGE_TAG" .
    - docker push $DOCKER_IMAGE_NAME_COASTAL:$DOCKER_IMAGE_TAG
    - docker logout

unit-test-bmi:
  stage: unit_test
  image: $DOCKER_IMAGE_NAME_BMI_FORCING:$DOCKER_IMAGE_TAG
  script:
    # TODO add unit tests when available
    - echo "Running BMI Forcing Unit Tests..."

unit-test-lumped:
  stage: unit_test
  image: $DOCKER_IMAGE_NAME_LUMPED_FORCING:$DOCKER_IMAGE_TAG
  script:
    # TODO add unit tests when available
    - echo "Running Lumped Forcing Unit Tests..."

unit-test-coastal:
  stage: unit_test
  image: $DOCKER_IMAGE_NAME_COASTAL:$DOCKER_IMAGE_TAG
  script:
    # TODO add unit tests when available
    - echo "Running Coastal Unit Tests..."

sonarqube:
  stage: sonarqube
  image:
    name: registry.sh.nextgenwaterprediction.com/infrastructure/sonar-scanner-cli/sonar-scanner-cli:5.0.1
    entrypoint: [""]
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    # Shallow cloning needs to be disabled.
    # See https://docs.sonarqube.org/latest/analysis/gitlab-cicd/.
    GIT_DEPTH: 0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -X -Dsonar.verbose=true
  allow_failure: true # FIXME

container_scanning:
  stage: test
  needs:
    - build
  variables:
    SECURE_LOG_LEVEL: info
    CS_SEVERITY_THRESHOLD: UNKNOWN
    CS_IMAGE: $DOCKER_IMAGE_NAME_BMI_FORCING:$DOCKER_IMAGE_TAG

container_scanning_2:
  extends: container_scanning
  stage: test
  needs:
    - build
  variables:
    SECURE_LOG_LEVEL: info
    CS_SEVERITY_THRESHOLD: UNKNOWN
    CS_IMAGE: $DOCKER_IMAGE_NAME_LUMPED_FORCING:$DOCKER_IMAGE_TAG

container_scanning_3:
  extends: container_scanning
  stage: test
  needs:
    - build
  variables:
    SECURE_LOG_LEVEL: info
    CS_SEVERITY_THRESHOLD: UNKNOWN
    CS_IMAGE: $DOCKER_IMAGE_NAME_COASTAL:$DOCKER_IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Logging in to Gitlab Container Registry to push the image..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Pushing to the docker registry"
    - docker tag $DOCKER_IMAGE_NAME_BMI_FORCING:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME_BMI_FORCING:latest
    - docker push $DOCKER_IMAGE_NAME_BMI_FORCING:latest
    - docker tag $DOCKER_IMAGE_NAME_LUMPED_FORCING:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME_LUMPED_FORCING:latest
    - docker push $DOCKER_IMAGE_NAME_LUMPED_FORCING:latest
    - docker tag $DOCKER_IMAGE_NAME_COASTAL:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME_COASTAL:latest
    - docker push $DOCKER_IMAGE_NAME_COASTAL:latest
    - docker logout
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
