# syntax=docker/dockerfile:1.4

##############################
# Stage: Base – Common Setup
##############################
FROM rockylinux:8 AS base

# cannot remove LANG even though https://bugs.python.org/issue19846 is fixed
# last attempted removal of LANG broke many users:
# https://github.com/docker-library/python/pull/570
ENV LANG="C.UTF-8" \
    \
    PYTHON_VERSION="3.10.14" \
    SZIP_VERSION="2.1.1" \
    HDF5_VERSION="1.10.11" \
    NETCDF_C_VERSION="4.7.4" \
    NETCDF_FORTRAN_VERSION="4.5.4" \
    BOOST_VERSION="1.83.0"

# Add conda repo
#RUN <<EOF cat > /etc/yum.repos.d/conda.repo
#[conda]
#name=Conda
#baseurl=https://repo.anaconda.com/pkgs/misc/rpmrepo/conda
#enabled=1
#gpgcheck=1
#gpgkey=https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
#EOF

# runtime dependencies
RUN set -eux && \
    dnf install -y epel-release && \
    dnf config-manager --set-enabled powertools && \
    dnf install -y \
        autoconf \
        automake \
        bc \
        cmake \
        curl curl-devel \
        file \
        findutils \
        conda \
        git \
## FIXME: replace GNU compilers with Intel compiler ##
        gcc-toolset-10 \
## FIXME: replace GNU compilers with Intel compiler ##
        gcc-toolset-10 \
        gcc-toolset-10-libasan-devel \
        libasan6 \
        libffi libffi-devel \
        m4 \
        udunits2 udunits2-devel \
        bzip2 bzip2-devel \
        zlib zlib-devel \
## FIXME: replace openmpi with Intel MPI libraries ##
        openmpi openmpi-devel \
        openssl openssl-devel \
        rsync \
        sqlite sqlite-devel \
        tk tk-devel \
        uuid uuid-devel \
        which \
        xz \
        jq \
    && dnf clean all && rm -rf /var/cache/dnf

## FIXME: replace GNU compilers with Intel compiler ##
SHELL [ "/usr/bin/scl", "enable", "gcc-toolset-10" ]
## FIXME: replace openmpi with Intel MPI libraries ##
ENV PATH="${PATH}:/usr/lib64/openmpi/bin/"

# Fix OpenMPI support within container
ENV PSM3_HAL=loopback \
    PSM3_DEVICES=self

ENV MINICONDA_VERSION="latest"
ENV MINICONDA_INSTALLER_URL="https://github.com/conda-forge/miniforge/releases/${MINICONDA_VERSION}/download/Miniforge3-Linux-x86_64.sh"

ENV CONDA_DIR="/opt/conda"

RUN curl --location --output ./miniforge.sh ${MINICONDA_INSTALLER_URL} && \
    bash ./miniforge.sh -b -p ${CONDA_DIR} && \
    rm ./miniforge.sh

RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-boost \
    set -eux && \
    curl --location --output boost.tar.gz https://archives.boost.io/release/${BOOST_VERSION%%[a-z]*}/source/boost_${BOOST_VERSION//./_}.tar.gz && \
    mkdir --parents /opt/boost && \
    tar --extract --directory /opt/boost --strip-components=1 --file boost.tar.gz && \
    rm boost.tar.gz \
    # build boost libraries
    && cd /opt/boost && ./bootstrap.sh && ./b2 && ./b2 install --prefix=/usr/local \
    && rm -rf /opt/boost

# Build Python from source and install it
RUN --mount=type=cache,target=/root/.cache/build-python,id=build-python \
	set -eux && \
    curl --location --output python.tar.xz "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz" && \
	mkdir --parents /usr/src/python && \
    tar --extract --directory /usr/src/python --strip-components=1 --file python.tar.xz && \
    rm python.tar.xz && \
    cd /usr/src/python && \
	./configure \
		--enable-loadable-sqlite-extensions \
		--enable-optimizations \
		--enable-option-checking=fatal \
		--enable-shared \
		--with-lto \
		--with-system-expat \
		--without-ensurepip && \
	nproc="$(nproc)" && \
	make -j "$nproc" "PROFILE_TASK=${PROFILE_TASK:-}" && \
# https://github.com/docker-library/python/issues/784
# prevent accidental usage of a system installed libpython of the same version
    rm python && \
	make -j "$nproc" \
		"LDFLAGS=${LDFLAGS:--Wl},-rpath='\$\$ORIGIN/../lib'" \
		"PROFILE_TASK=${PROFILE_TASK:-}" \
        python && \
    make install && \
# enable GDB to load debugging data: https://github.com/docker-library/python/pull/701
    bin="$(readlink -ve /usr/local/bin/python3)" && \
    dir="$(dirname "$bin")" && \
    mkdir --parents "/usr/share/gdb/auto-load/$dir" && \
    cp -vL Tools/gdb/libpython.py "/usr/share/gdb/auto-load/$bin-gdb.py" && \
    cd / && \
    rm -rf /usr/src/python && \
    find /usr/local -depth \
        \( \
            \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
            -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \
        \) -exec rm -rf '{}' + && \
    ldconfig && \
    python3 --version

# make some useful symlinks that are expected to exist ("/usr/local/bin/python" and friends)
RUN set -eux && \
	for src in idle3 pydoc3 python3 python3-config; do \
		dst="$(echo "$src" | tr -d 3)"; \
		[ -s "/usr/local/bin/$src" ]; \
		[ ! -e "/usr/local/bin/$dst" ]; \
		ln -svT "$src" "/usr/local/bin/$dst"; \
	done

ENV VIRTUAL_ENV="/ngen-app/ngen-python"

# Create virtual environment for the application and upgrade pip within it
RUN set -eux; python3 -m venv ${VIRTUAL_ENV}

# python3.10 -m venv ${VIRTUAL_ENV}

ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
    set -eux && \
    pip3 install --upgrade pip setuptools wheel && \
    pip3 install 'numpy==1.26.4' 'netcdf4<=1.6.3'

RUN set -eux; \
	\
	curl --location --output szip.gz "https://docs.hdfgroup.org/archive/support/ftp/lib-external/szip/${SZIP_VERSION%%[a-z]*}/src/szip-${SZIP_VERSION}.tar.gz"; \
	mkdir --parents /usr/src/szip; \
	tar --extract --directory /usr/src/szip --strip-components=1 --file szip.gz; \
	rm szip.gz; \
	\
	cd /usr/src/szip; \
	./configure --prefix=/usr/local/ \
	; \
	nproc="$(nproc)"; \
	make -j "$nproc" \
	; \
	make install ; \
    \
    rm --recursive --force /usr/src/szip

RUN set -eux; \
	\
	curl --location --output libhdf5.tar.gz "https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5-${HDF5_VERSION//./_}.tar.gz"; \
	mkdir --parents /usr/src/hdf5; \
	tar --extract --directory /usr/src/hdf5 --strip-components=1 --file libhdf5.tar.gz; \
	rm libhdf5.tar.gz; \
	\
	cd /usr/src/hdf5; \
	./configure --prefix=/usr/local/ --with-szlib=/usr/local/ \
	; \
	nproc="$(nproc)"; \
	make check -j "$nproc" \
	; \
    make install ; \
    \
    rm --recursive --force /usr/src/hdf5

RUN set -eux; \
    \
    curl --location --output netcdf-c.tar.gz "https://github.com/Unidata/netcdf-c/archive/refs/tags/v${NETCDF_C_VERSION%%[a-z]*}.tar.gz"; \
    mkdir --parents /usr/src/netcdf-c; \
    tar --extract --directory /usr/src/netcdf-c --strip-components=1 --file netcdf-c.tar.gz; \
    rm netcdf-c.tar.gz; \
    \
    cd /usr/src/netcdf-c; \
    cmake -B cmake_build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DENABLE_TESTS=OFF \
    ; \
    nproc="$(nproc)"; \
    cmake --build cmake_build --parallel "$nproc" \
    ; \
    cmake --build cmake_build --target install ; \
    \
    rm --recursive --force /usr/src/netcdf-c

RUN set -eux; \
    \
    curl --location --output netcdf-fortran.tar.gz "https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v${NETCDF_FORTRAN_VERSION%%[a-z]*}.tar.gz"; \
    mkdir --parents /usr/src/netcdf-fortran; \
    tar --extract --directory /usr/src/netcdf-fortran --strip-components=1 --file netcdf-fortran.tar.gz; \
    rm netcdf-fortran.tar.gz; \
    \
    cd /usr/src/netcdf-fortran; \
    cmake -B cmake_build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DENABLE_TESTS=OFF \
    -DCMAKE_Fortran_COMPILER=/opt/rh/gcc-toolset-10/root/usr/bin/gfortran \
    ; \
    nproc="$(nproc)"; \
    cmake --build cmake_build --parallel "$nproc" \
    ; \
    cmake --build cmake_build --target install ; \
    \
    rm --recursive --force /usr/src/netcdf-fortran

#Env for netcdf-fortran
ENV LD_LIBRARY_PATH=/usr/local/lib64

RUN set -eux; \
    curl --location --output wgrib2.tgz "https://ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2.tgz" ; \
    mkdir --parents /usr/src/wgrib2 ; \
    tar --extract --directory /usr/src/wgrib2 --strip-components=1 --file wgrib2.tgz ; \
    rm wgrib2.tgz ; \
    cd /usr/src/wgrib2 ; \
    export CC=gcc ; \
    export FC=gfortran ; \
    make \
        USE_IPOLATES=3 \
        USE_PNG=1 \
        USE_AEC=0 \
        USE_JASPER=1 \
        USE_OPENJPEG=0 \
        USE_G2CLIB=0 \
        PREFIX=/usr/local ; \
    make lib ; \
    cp /usr/src/wgrib2/wgrib2/wgrib2 /usr/local/bin/ ; \
    chmod +x /usr/local/bin/wgrib2 ; \
    rm --recursive --force /usr/src/wgrib2

#build the OTPSnc binary
RUN set -eux && \
    \
    curl "https://drive.usercontent.google.com/download?id=10uz0PJBJHd3kzOiH5IeVz_Ml1Zct4gTj&confirm=xxx" -o OTPSnc.tar.gz && \
    mkdir --parents /ngen-app/OTPSnc && \
    tar --extract --directory /ngen-app/OTPSnc --strip-components=1 --file OTPSnc.tar.gz && \
    rm OTPSnc.tar.gz && \
    rm -f /ngen-app/OTPSnc/DATA/load_file.nc && \
    \
    cd /ngen-app/OTPSnc && \
    sed -i 's/usr\/local\/lib/usr\/local\/lib64/' makefile; \
    make -f makefile ; \
    cd -

WORKDIR /ngen-app/

# TODO This will invalidate the cache for all subsequent stages so we don't really want to do this
# check out the ngen repo
RUN set -eux && \
    git clone -b development --recurse-submodules https://github.com/NGWPC/ngen.git && \
    cd ngen && \
    git submodule update --init --recursive

# check out the github t-route development branch repo
# the t-route repo on gitlab doesn't work with the HF v2.2 in the
# Lower Colorado River domain
RUN set -eux && \
    git clone -b development https://github.com/NGWPC/t-route.git

##############################
# Stage: Submodules Build
##############################
#FROM base AS submodules

SHELL [ "/usr/bin/scl", "enable", "gcc-toolset-10" ]

WORKDIR /ngen-app/ngen/

# Install Python dependencies and remove the temporary requirements files
RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
    set -eux && ls -l ./extern/ && \
        pip3 install -r extern/test_bmi_py/requirements.txt && \
        pip3 install -r extern/t-route/requirements.txt

ENV LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH

# Use cache for building the t-route submodule
# use the development branch on github
RUN --mount=type=cache,target=/root/.cache/t-route,id=t-route-build \
    set -eux && \
    cd /ngen-app/t-route && \
   echo "Running compiler.sh" && \
    LDFLAGS='-Wl,-L/usr/local/lib64/,-L/usr/local/lib/,-rpath,/usr/local/lib64/,-rpath,/usr/local/lib/' && \
    ./compiler.sh no-e

# Configure the build with cache for CMake
RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-ngen \
    set -eux && \
        cmake -B cmake_build -S . \
## FIXME: figure out why running with MPI enabled throws errors
##      and re-enable it.
          -DNGEN_WITH_MPI=ON \
          -DNGEN_WITH_NETCDF=ON \
          -DNGEN_WITH_SQLITE=ON \
          -DNGEN_WITH_UDUNITS=ON \
          -DNGEN_WITH_BMI_FORTRAN=ON \
          -DNGEN_WITH_BMI_C=ON \
          -DNGEN_WITH_PYTHON=ON \
          -DNGEN_WITH_TESTS=OFF \
          -DNGEN_WITH_ROUTING=ON \
          -DNGEN_QUIET=ON \
          -DNGEN_UPDATE_GIT_SUBMODULES=OFF \
          -DBOOST_ROOT=/usr/local && \
      cmake --build cmake_build --target all --parallel $(nproc)

# Build each submodule in a separate layer, using cache for CMake as well
RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-lasam \
    set -eux && \
    cmake -B extern/LASAM/cmake_build -S extern/LASAM/ -DNGEN=ON && \
    cmake --build extern/LASAM/cmake_build/

RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-snow17 \
    set -eux && \
    cmake -B extern/snow17/cmake_build -S extern/snow17/ && \
    cmake --build extern/snow17/cmake_build/

RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-sac-sma \
    set -eux && \
    cmake -B extern/sac-sma/cmake_build -S extern/sac-sma/ && \
    cmake --build extern/sac-sma/cmake_build/

RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-soilmoistureprofiles \
    set -eux && \
    cmake -B extern/SoilMoistureProfiles/cmake_build -S extern/SoilMoistureProfiles/SoilMoistureProfiles/ -DNGEN=ON && \
    cmake --build extern/SoilMoistureProfiles/cmake_build/

RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-soilfreezethaw \
    set -eux && \
    cmake -B extern/SoilFreezeThaw/cmake_build -S extern/SoilFreezeThaw/SoilFreezeThaw/ -DNGEN=ON && \
    cmake --build extern/SoilFreezeThaw/cmake_build/

RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-ueb-bmi \
    set -eux && \
    cmake -B extern/ueb-bmi/cmake_build -S extern/ueb-bmi/ -DBMICXX_INCLUDE_DIRS=/ngen-app/ngen/extern/bmi-cxx/ && \
    cmake --build extern/ueb-bmi/cmake_build/

RUN set -eux && \
    mkdir --parents /ngencerf/data/ngen-run-logs/ && \
    mkdir --parents /ngen-app/bin/ && \
    mv run-ngen.sh /ngen-app/bin/ && \
    chmod +x /ngen-app/bin/run-ngen.sh

WORKDIR /ngen-app/ngen

# --- Git Info Extraction with Submodules ---
# Extract Git information for the main repository
ARG CI_COMMIT_REF_NAME

RUN set -eux && \
    # Get the remote URL from Git configuration
    repo_url=$(git config --get remote.origin.url); \
    # Remove trailing slash if present
    repo_url=${repo_url%/}; \
    # Extract the repo name (everything after the last slash) and remove any trailing .git
    key=${repo_url##*/}; \
    key=${key%.git}; \
    # Construct the file path using the derived key
    export GIT_INFO_PATH="/ngen-app/${key}_git_info.json"; \
    # Determine branch name: use CI_COMMIT_REF_NAME if set; otherwise, use git's current branch
    branch=$( [ -n "${CI_COMMIT_REF_NAME:-}" ] && echo "${CI_COMMIT_REF_NAME}" || git rev-parse --abbrev-ref HEAD ); \
    jq -n \
      --arg commit_hash "$(git rev-parse HEAD)" \
      --arg branch "$branch" \
      --arg tags "$(git tag --points-at HEAD | tr '\n' ' ')" \
      --arg author "$(git log -1 --pretty=format:'%an')" \
      --arg commit_date "$(date -u -d @$(git log -1 --pretty=format:'%ct') +'%Y-%m-%d %H:%M:%S UTC')" \
      --arg message "$(git log -1 --pretty=format:'%s' | tr '\n' ';')" \
      --arg build_date "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
      "{\"$key\": {commit_hash: \$commit_hash, branch: \$branch, tags: \$tags, author: \$author, commit_date: \$commit_date, message: \$message, build_date: \$build_date}}" \
      > $GIT_INFO_PATH; \
    \
    # Create directory for submodule JSON files
    mkdir -p /ngen-app/submodules-json; \
    \
    # Process each submodule listed in .gitmodules (skipping unwanted ones)
    for sub in $(git config --file .gitmodules --get-regexp path | awk '{print $2}'); do \
      cd "$sub"; \
      # Derive submodule key from its remote URL
      subrepo_url=$(git config --get remote.origin.url); \
      # Remove trailing slash if present
      subrepo_url=${subrepo_url%/}; \
      sub_key=${subrepo_url##*/}; \
      sub_key=${sub_key%.git}; \
      \
      # Skip unwanted submodules based on the derived key
      if [[ "$sub_key" == "googletest" || "$sub_key" == "pybind11" || "$sub_key" == "netcdf-cxx4" ]]; then \
        cd - > /dev/null; \
        continue; \
      fi; \
      \
      # Try to find a preferred branch (development, release-candidate, main, or master) that contains the current commit
      sub_branch=$( \
        git branch -r --contains HEAD | grep -v '\->' | \
        grep -E 'origin/(development|release-candidate|main|master)' | \
        sed 's|origin/||' | head -n1 | xargs \
      ); \
      \
      # If none of the preferred branches contain the commit, fall back to any branch that does
      if [ -z "$sub_branch" ]; then \
        sub_branch=$(git branch -r --contains HEAD | grep -v '\->' | sed 's|origin/||' | head -n1 | xargs); \
      fi; \
      \
      # If no branches at all contain the commit, use "HEAD" as a fallback
      sub_branch=${sub_branch:-HEAD}; \
      \
      info=$(jq -n \
        --arg commit_hash "$(git rev-parse HEAD)" \
        --arg branch "$sub_branch" \
        --arg tags "$(git tag --points-at HEAD | tr '\n' ' ')" \
        --arg author "$(git log -1 --pretty=format:%an)" \
        --arg commit_date "$(date -u -d @$(git log -1 --pretty=format:%ct) +'%Y-%m-%d %H:%M:%S UTC')" \
        --arg message "$(git log -1 --pretty=format:%s | tr '\n' ' ')" \
        --arg build_date "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
        '{"'"$sub_key"'": {commit_hash: $commit_hash, branch: $branch, tags: $tags, author: $author, commit_date: $commit_date, message: $message, build_date: $build_date}}' ); \
      cd - > /dev/null; \
      echo "$info" > /ngen-app/submodules-json/git_info_"$sub_key".json; \
    done; \
    \
    # Merge the main repository JSON with all submodule JSON files as top-level objects
    jq -s 'add' $GIT_INFO_PATH /ngen-app/submodules-json/*.json > /ngen-app/merged_git_info.json && \
    mv /ngen-app/merged_git_info.json $GIT_INFO_PATH && \
    rm -rf /ngen-app/submodules-json

# add conda and OTPSnc to the PATH
ENV PATH=/opt/conda/bin:/ngen-app/OTPSnc:${PATH}

# check out the nwm.v3.0.6_no_svn repo
RUN set -eux; \
    \
   git clone -b main https://github.com/NGWPC/nwm.v3.0.6_no_svn.git /ngen-app/nwm.v3.0.6

RUN set -eux; mkdir -p /ngen-app/nwm.v3.0.6/exec

RUN set -eux;  mkdir -p /ngen-app/nwm.v3.0.6/parm

#RUN --mount=type=secret,id=aws \
#    set -eux; \
#    AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws \
#    aws s3 cp s3://ngwpc-data/NWM_Parm_v3.0/coastal.tar.gz ./; \
#    tar -zxvf coastal.tar.gz -C /ngen-app/nwm.v3.0.6/parm/; \
#    rm -f coastal.tar.gz
#
#RUN --mount=type=secret,id=aws \
#    set -eux; \
#    AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws \
#    aws s3 cp s3://ngwpc-data/NWM_Parm_v3.0/domain.tar.gz ./; \
#    tar -zxvf domain.tar.gz -C /ngen-app/nwm.v3.0.6/parm/ domain/geo_em_CONUS.nc ; \
#    rm -f domain.tar.gz
#
#RUN --mount=type=secret,id=aws \
#    set -eux; \
#    AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws \
#    aws s3 cp s3://ngwpc-data/NWM_Parm_v3.0/domain_hawaii.tar.gz ./; \
#    tar -zxvf domain_hawaii.tar.gz -C /ngen-app/nwm.v3.0.6/parm/ domain_hawaii/geo_em_HI.nc ; \
#    rm -f domain_hawaii.tar.gz
#
#RUN --mount=type=secret,id=aws \
#    set -eux; \
#    AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws \
#    aws s3 cp s3://ngwpc-data/NWM_Parm_v3.0/domain_puertorico.tar.gz ./; \
#    tar -zxvf domain_puertorico.tar.gz -C /ngen-app/nwm.v3.0.6/parm/ domain_puertorico/geo_em_PRVI.nc ; \
#    rm -f domain_puertorico.tar.gz

#build the SCHISM binaries
RUN set -eux; \
    \
    cd /ngen-app/nwm.v3.0.6/sorc/schism/; \
    source ./build_schism_cmake_docker.sh; \
    cd /ngen-app/nwm.v3.0.6/sorc/combine_sink_source; \
    make; \
    cp combine_sink_source ../../exec;\
    cd /ngen-app/nwm.v3.0.6/sorc/combine_hotstart7; \
    make; \
    cp combine_hotstart7 ../../exec; \
    cd /ngen-app/nwm.v3.0.6/sorc/metis_prep; \
    make clean; make; \
    cp metis_prep ../../exec; \
    cd /ngen-app/nwm.v3.0.6/sorc/metis; \
    source ./build_metis_docker.sh; \
    cd -

ENV CONDA_ENVS_PATH=/ngen-app/conda/envs/

ARG CONDA_ENV_NAME=ngen_forcing_coastal
COPY ./coastal/environment.yml environment.yaml
RUN set -eux; \
    \
    conda init

RUN set -eux; \
    \
    conda env create --name ${CONDA_ENV_NAME} --file=environment.yaml ; \
    conda clean --all --yes ; \
    rm --force environment.yaml

#RUN set -eux; \
#    \
#    conda init bash
#RUN set -eux; \
#    \
#    conda init ${CONDA_ENV_NAME}

#ARG OLD_PATH=${PATH}
#ENV PATH=${CONDA_ENVS_PATH}/${CONDA_ENV_NAME}/bin:${PATH}

ARG CONDA_ENV_NAME=ngen_forcings_engine_bmi
COPY ./NextGen_Forcings_Engine_BMI/environment.yml environment.yaml
RUN set -eux; \
    \
    conda env create --name ${CONDA_ENV_NAME} --file=environment.yaml ; \
    conda clean --all --yes ; \
    rm --force environment.yaml

ARG CONDA_ENV_NAME=ngen_esmf_mesh_domain
COPY ./ESMF_Mesh_Domain_Configuration_Production/environment.yml environment.yaml
RUN set -eux; \
    \
    conda env create --name ${CONDA_ENV_NAME} --file=environment.yaml ; \
    conda clean --all --yes ; \
    conda run -n ${CONDA_ENV_NAME} pip install --upgrade geopandas ; \
    rm --force environment.yaml

ENV WGRIB2=/usr/local/bin/wgrib2

#ENV PATH=${OLD_PATH}

COPY . /ngen-app/ngen-forcing/

WORKDIR /ngen-app/

ENV COASTAL_VENV="/ngen-app/ngen-forcing-coastal"
RUN set -eux; python3 -m venv ${COASTAL_VENV}

RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
    set -eux && \
    ${COASTAL_VENV}/bin/python -m pip install -r ./ngen-forcing/coastal/forecast/requirements.txt

ENV SFINCS_VENV="/ngen-app/ngen-forcing-sfincs"
RUN set -eux; python3 -m venv ${SFINCS_VENV}

RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
    set -eux && \
    ${SFINCS_VENV}/bin/python -m pip install -r ./ngen-forcing/coastal/SFINCS/requirements.txt

RUN set -eux; \
    \
    rm --force /root/.gitconfig

WORKDIR /
SHELL ["/bin/bash", "-c"]

ENTRYPOINT [ "/bin/bash" ]
