[pytest]
pythonpath = .
log_cli = True
log_cli_level = INFO
; log_cli_level = DEBUG
addopts = --full-trace -vv
testpaths =
    tests/esmf_regrid
    tests/geomod
    tests/input_forcing
    tests/supp_precip
    tests/ana
    tests/bmi_model
    tests/config_options
