from NextGen_Forcings_Engine_BMI.NextGen_Forcings_Engine.core import (
    regrid,
    time_handling,
)
from NextGen_Forcings_Engine_BMI.NextGen_Forcings_Engine.core.timeInterpMod import (
    nearest_neighbor,
    no_interpolation,
    weighted_average,
)

GEOMOD = {
    "GeoMeta": [
        "nodeCoords",
        "centerCoords",
        "inds",
        "esmf_lat",
        "esmf_lon",
    ],
    "UnstructuredGeoMeta": [
        "x_lower_bound",
        "x_upper_bound",
        "y_lower_bound",
        "y_upper_bound",
        "dx_meters",
        "dy_meters",
        "element_ids",
        "element_ids_global",
        "sina_grid",
        "cosa_grid",
        "esmf_lat",
        "esmf_lon",
    ],
    "HydrofabricGeoMeta": [
        "nx_local_elem",
        "ny_local_elem",
        "x_lower_bound",
        "x_upper_bound",
        "y_lower_bound",
        "y_upper_bound",
        "nx_global_elem",
        "ny_global_elem",
        "dx_meters",
        "dy_meters",
        "mesh_inds_elem",
        "height_elem",
        "sina_grid",
        "cosa_grid",
        "slope_elem",
        "slp_azi_elem",
        "esmf_lat",
        "esmf_lon",
        "latitude_grid_elem",
        "longitude_grid_elem",
    ],
    "GriddedGeoMeta": [
        "nx_local_elem",
        "ny_local_elem",
        "nx_global_elem",
        "ny_global_elem",
        "element_ids",
        "element_ids_global",
        "lat_bounds",
        "lon_bounds",
        "mesh_inds",
        "mesh_inds_elem",
        "height_elem",
        "slope_elem",
        "slp_azi_elem",
        "latitude_grid_elem",
        "longitude_grid_elem",
    ],
}
BMI_MODEL = {
    "att_map": {
        "model_name": "NWMv3.0 Forcings Engine BMI Python",
        "version": "1.0",
        "author_name": "Jason Ducker",
        "grid_type": "unstructured&uniform_rectilinear",
        "time_units": "seconds",
    },
    "extension_map": {
        "gridded": "GRIDDED",
        "hydrofabric": "HYDROFABRIC",
        "unstructured": "MESH",
    },
    "_output_var_names": [
        "U2D_ELEMENT",
        "V2D_ELEMENT",
        "LWDOWN_ELEMENT",
        "SWDOWN_ELEMENT",
        "T2D_ELEMENT",
        "Q2D_ELEMENT",
        "PSFC_ELEMENT",
        "RAINRATE_ELEMENT",
    ],
    "_output_var_names_unstructured": [
        "U2D_NODE",
        "V2D_NODE",
        "LWDOWN_NODE",
        "SWDOWN_NODE",
        "T2D_NODE",
        "Q2D_NODE",
        "PSFC_NODE",
        "RAINRATE_NODE",
    ],
    "_var_name_units_map": {
        "U2D_ELEMENT": ["10-m U-component of wind", "m/s"],
        "V2D_ELEMENT": ["10-m V-component of wind", "m/s"],
        "T2D_ELEMENT": ["2-m Air Temperature", "K"],
        "Q2D_ELEMENT": ["2-m Specific Humidity", "kg/kg"],
        "LWDOWN_ELEMENT": [
            "Surface downward long-wave radiation flux",
            "W/m^2",
        ],
        "SWDOWN_ELEMENT": [
            "Surface downward short-wave radiation flux",
            "W/m^2",
        ],
        "PSFC_ELEMENT": ["Surface Pressure", "Pa"],
        "RAINRATE_ELEMENT": ["Surface Precipitation Rate", "mm/s"],
    },
    "_var_name_units_map_unstructured": {
        "U2D_NODE": ["10-m U-component of wind", "m/s"],
        "V2D_NODE": ["10-m V-component of wind", "m/s"],
        "T2D_NODE": ["2-m Air Temperature", "K"],
        "Q2D_NODE": ["2-m Specific Humidity", "kg/kg"],
        "LWDOWN_NODE": [
            "Surface downward long-wave radiation flux",
            "W/m^2",
        ],
        "SWDOWN_NODE": [
            "Surface downward short-wave radiation flux",
            "W/m^2",
        ],
        "PSFC_NODE": ["Surface Pressure", "Pa"],
        "RAINRATE_NODE": ["Surface Precipitation Rate", "mm/s"],
    },
}
FORCINGINPUTMOD = {
    "InputForcings": [
        "nx_global",
        "ny_global",
        "nx_local",
        "ny_local",
        "nx_local_corner",
        "ny_local_corner",
        "x_lower_bound",
        "x_upper_bound",
        "y_lower_bound",
        "y_upper_bound",
        "x_lower_bound_corner",
        "x_upper_bound_corner",
        "y_lower_bound_corner",
        "y_upper_bound_corner",
        "outFreq",
        "lapseGrid",
        "rqiClimoGrid",
        "nwmPRISM_numGrid",
        "nwmPRISM_denGrid",
        "esmf_lats",
        "esmf_lons",
        "esmf_grid_in",
        "esmf_grid_in_elem",
        "regridObj",
        "regridObj_elem",
        "esmf_field_in",
        "esmf_field_in_elem",
        "esmf_field_out",
        "esmf_field_out_elem",
        # --------------------------------
        # Only used for CFSv2 bias correction
        # as bias correction needs to take
        # place prior to regridding.
        "coarse_input_forcings1",
        "coarse_input_forcings2",
        # --------------------------------
        "regridded_forcings1",
        "regridded_forcings2",
        "globalPcpRate1",
        "globalPcpRate2",
        "regridded_forcings1_elem",
        "regridded_forcings2_elem",
        "globalPcpRate1_elem",
        "globalPcpRate2_elem",
        "ndv",
        "file_in1",
        "file_in2",
        "fcst_hour1",
        "fcst_hour2",
        "fcst_date1",
        "fcst_date2",
        "tmpFile",
        "tmpFileHeight",
        "regridded_precip1",
        "regridded_precip2",
        "regridded_precip1_elem",
        "regridded_precip2_elem",
        "_grib_vars",
        "_cycle_freq",
        "_t2dTmp",
        "_psfcTmp",
        "_final_forcings",
        "_height",
        "_regridded_mask",
        "_regridded_mask_AORC",
    ],
    "InputForcingsGridded": [
        "t2dTmp_elem",
        "psfcTmp_elem",
        "final_forcings_elem",
        "height_elem",
        "regridded_mask_elem",
        "regridded_mask_elem_AORC",
    ],
    "InputForcingsHydrofabric": [
        "final_forcings_elem",
        "height_elem",
        "regridded_mask_elem",
        "regridded_mask_elem_AORC",
        "t2dTmp_elem",
        "psfcTmp_elem",
    ],
    "InputForcingsUnstructured": [
        "_t2dTmp_elem",
        "_psfcTmp_elem",
        "_final_forcings_elem",
        "_height_elem",
        "_regridded_mask_elem",
        "_regridded_mask_elem_AORC",
    ],
    "PRODUCT_NAME": {
        1: "NLDAS2_GRIB1",
        2: "NARR_GRIB1",
        3: "GFS_Production_GRIB2",
        4: "NAM_Conus_Nest_GRIB2",
        5: "HRRR_Conus_GRIB2",
        6: "RAP_Conus_GRIB2",
        7: "CFSv2_6Hr_Global_GRIB2",
        8: "WRF_ARW_Hawaii_GRIB2",
        9: "GFS_Production_025d_GRIB2",
        10: "Custom_NetCDF_Hourly",
        11: "Custom_NetCDF_Hourly",
        12: "AORC",
        13: "NAM_Nest_3km_Hawaii",
        14: "NAM_Nest_3km_PuertoRico",
        15: "NAM_Nest_3km_Alaska",
        16: "NAM_Nest_3km_Hawaii_Radiation-Only",
        17: "NAM_Nest_3km_PuertoRico_Radiation-Only",
        18: "WRF_ARW_PuertoRico_GRIB2",
        19: "HRRR_Alaska_GRIB2",
        20: "Alaska_AnA",
        21: "AORC_Alaska",
        22: "Alaska_ExtAnA",
        23: "ERA5",
        24: "NBM",
        25: "NDFD",
        26: "HRRR_15min",
        27: "NWM",
    },
    "CYCLE_FREQ": {
        1: 60,
        2: 180,
        3: 360,
        4: 360,
        5: 60,
        6: 60,
        7: 360,
        8: 1440,
        9: 360,
        10: -9999,
        11: -9999,
        12: -9999,
        13: 360,
        14: 360,
        15: 360,
        16: 360,
        17: 360,
        18: 1440,
        19: 180,
        20: 180,
        21: -9999,
        22: 180,
        23: -9999,
        24: 60,
        25: 1440,
        26: 15,
        27: -9999,
    },
    "GRIB_VARS": {
        1: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        2: None,
        3: [
            "TMP",
            "SPFH",
            "UGRD",
            "VGRD",
            "PRATE",
            "DSWRF",
            "DLWRF",
            "PRES",
            "CPOFP",
        ],
        4: None,
        5: [
            "TMP",
            "SPFH",
            "UGRD",
            "VGRD",
            "APCP",
            "DSWRF",
            "DLWRF",
            "PRES",
            "CPOFP",
        ],
        6: [
            "TMP",
            "SPFH",
            "UGRD",
            "VGRD",
            "APCP",
            "DSWRF",
            "DLWRF",
            "PRES",
            "FROZR",
        ],
        7: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        8: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "PRES"],
        9: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        10: None,
        11: None,
        12: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        13: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        14: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        15: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        16: ["DSWRF", "DLWRF"],
        17: ["DSWRF", "DLWRF"],
        18: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "PRES"],
        19: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        20: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        21: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        22: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        23: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        24: ["TMP", "APCP"],
        25: ["TMP", "WDIR", "WSPD", "APCP"],
        26: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        27: [
            "T2D",
            "Q2D",
            "U2D",
            "V2D",
            "RAINRATE",
            "SWDOWN",
            "LWDOWN",
            "PSFC",
        ],
    },
    "GRIB_LEVELS": {
        1: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        2: None,
        3: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        4: None,
        5: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        6: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        7: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        8: [
            "80 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
        ],
        9: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        10: None,
        11: None,
        12: None,
        13: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        14: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        15: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        16: ["surface", "surface"],
        17: ["surface", "surface"],
        18: [
            "80 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
        ],
        19: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        20: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        21: None,
        22: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        23: None,
        24: ["2 m above ground", "surface"],
        25: [
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
        ],
        26: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        27: None,
    },
    "NET_CDF_VARS_NAMES": {
        1: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        2: None,
        3: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
            "CPOFP_surface",
        ],
        4: None,
        5: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
            "CPOFP_surface",
        ],
        6: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
            "FROZR_surface",
        ],
        7: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        8: [
            "TMP_80maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "PRES_surface",
        ],
        9: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        10: ["T2D", "Q2D", "U10", "V10", "RAINRATE", "DSWRF", "DLWRF", "PRES"],
        11: ["T2D", "Q2D", "U10", "V10", "RAINRATE", "DSWRF", "DLWRF", "PRES"],
        12: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        13: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        14: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        15: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        16: ["DSWRF_surface", "DLWRF_surface"],
        17: ["DSWRF_surface", "DLWRF_surface"],
        18: [
            "TMP_80maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "PRES_surface",
        ],
        19: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        20: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        21: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        22: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        23: ["t2m", "d2m", "u10", "v10", "mtpr", "msdwswrf", "msdwlwrf", "sp"],
        24: ["TMP_2maboveground", "APCP_surface"],
        25: [
            "TMP_2maboveground",
            "WDIR_10maboveground",
            "WIND_10maboveground",
            "APCP_surface",
        ],
        26: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        27: ["T2D", "Q2D", "U2D", "V2D", "RAINRATE", "SWDOWN", "LWDOWN", "PSFC"],
    },
    "GRIB_MES_IDX": {
        1: None,
        2: None,
        3: None,
        4: None,
        5: None,
        6: None,
        7: None,
        8: None,
        9: [33, 34, 39, 40, 43, 88, 91, 6],
        10: None,
        11: None,
        12: None,
        13: None,
        14: None,
        15: None,
        16: None,
        17: None,
        18: None,
        19: None,
        20: None,
        21: None,
        22: None,
        23: None,
        24: None,
        25: None,
        26: None,
        27: None,
    },
    "INPUT_MAP_OUTPUT": {
        1: [4, 5, 0, 1, 3, 7, 2, 6],
        2: None,
        3: [4, 5, 0, 1, 3, 7, 2, 6, 8],
        4: None,
        5: [4, 5, 0, 1, 3, 7, 2, 6, 8],
        6: [4, 5, 0, 1, 3, 7, 2, 6, 8],
        7: [4, 5, 0, 1, 3, 7, 2, 6],
        8: [4, 5, 0, 1, 3, 6],
        9: [4, 5, 0, 1, 3, 7, 2, 6],
        10: [4, 5, 0, 1, 3, 7, 2, 6],
        11: [4, 5, 0, 1, 3, 7, 2, 6],
        12: [4, 5, 0, 1, 3, 7, 2, 6],
        13: [4, 5, 0, 1, 3, 7, 2, 6],
        14: [4, 5, 0, 1, 3, 7, 2, 6],
        15: [4, 5, 0, 1, 3, 7, 2, 6],
        16: [7, 2],
        17: [7, 2],
        18: [4, 5, 0, 1, 3, 6],
        19: [4, 5, 0, 1, 3, 7, 2, 6],
        20: [4, 5, 0, 1, 3, 7, 2, 6],
        21: [4, 5, 0, 1, 3, 7, 2, 6],
        22: [4, 5, 0, 1, 3, 7, 2, 6],
        23: [4, 5, 0, 1, 3, 7, 2, 6],
        24: [4, 3],
        25: [4, 0, 1, 3],
        26: [4, 5, 0, 1, 3, 7, 2, 6],
        27: [4, 5, 0, 1, 3, 7, 2, 6],
    },
    "FORECAST_HORIZONS": {
        1: None,
        2: None,
        3: None,
        4: None,
        5: [
            18,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
        ],
        6: [
            21,
            21,
            21,
            39,
            21,
            21,
            21,
            21,
            21,
            39,
            21,
            21,
            21,
            21,
            21,
            39,
            21,
            21,
            21,
            21,
            21,
            39,
            21,
            21,
        ],
        7: None,
        8: None,
        9: None,
        10: None,
        11: None,
        12: None,
        13: None,
        14: None,
        15: None,
        16: None,
        17: None,
        18: None,
        19: None,
        20: None,
        21: None,
        22: None,
        23: None,
        24: None,
        25: None,
        26: [
            18,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
        ],
        27: None,
    },
    "FIND_NEIGHBOR_FILES_MAP": {
        1: time_handling.find_nldas_neighbors,
        3: time_handling.find_gfs_neighbors,
        5: time_handling.find_conus_hrrr_neighbors,
        6: time_handling.find_conus_rap_neighbors,
        7: time_handling.find_cfsv2_neighbors,
        8: time_handling.find_hourly_wrf_arw_neighbors,
        9: time_handling.find_gfs_neighbors,
        10: time_handling.find_custom_hourly_neighbors,
        11: time_handling.find_custom_hourly_neighbors,
        12: time_handling.find_aorc_neighbors,
        13: time_handling.find_nam_nest_neighbors,
        14: time_handling.find_nam_nest_neighbors,
        15: time_handling.find_nam_nest_neighbors,
        16: time_handling.find_nam_nest_neighbors,
        17: time_handling.find_nam_nest_neighbors,
        18: time_handling.find_hourly_wrf_arw_neighbors,
        19: time_handling.find_ak_hrrr_neighbors,
        20: time_handling.find_ak_hrrr_neighbors,
        21: time_handling.find_aorc_neighbors,
        22: time_handling.find_ak_hrrr_neighbors,
        23: time_handling.find_era5_neighbors,
        24: time_handling.find_hourly_nbm_neighbors,
        25: time_handling.find_ndfd_neighbors,
        26: time_handling.find_input_neighbors,
        27: time_handling.find_nwm_neighbors,
    },
    "REGRID_MAP": {
        1: regrid.regrid_conus_rap,
        3: regrid.regrid_gfs,
        5: regrid.regrid_conus_hrrr,
        6: regrid.regrid_conus_rap,
        7: regrid.regrid_cfsv2,
        8: regrid.regrid_hourly_wrf_arw,
        9: regrid.regrid_gfs,
        10: regrid.regrid_custom_hourly_netcdf,
        11: regrid.regrid_custom_hourly_netcdf,
        12: regrid.regrid_custom_hourly_netcdf,
        13: regrid.regrid_nam_nest,
        14: regrid.regrid_nam_nest,
        15: regrid.regrid_nam_nest,
        16: regrid.regrid_nam_nest,
        17: regrid.regrid_nam_nest,
        18: regrid.regrid_hourly_wrf_arw,
        19: regrid.regrid_conus_hrrr,
        20: regrid.regrid_conus_hrrr,
        21: regrid.regrid_custom_hourly_netcdf,
        22: regrid.regrid_conus_hrrr,
        23: regrid.regrid_era5,
        24: regrid.regrid_hourly_nbm,
        25: regrid.regrid_ndfd,
        26: regrid.regrid_conus_hrrr,
        27: regrid.regrid_nwm,
    },
    "TEMPORAL_INTERPOLATE_INPUTS_MAP": {
        0: no_interpolation,
        1: nearest_neighbor,
        2: weighted_average,
    },
    "FILE_EXT": {
        "GRIB1": ".grb",
        "GRIB2": ".grib2",
        "NETCDF": ".nc",
        "NETCDF4": ".nc4",
        "NWM": ".LDASIN_DOMAIN1",
        "ZARR": ".zarr",
        "GRIB2_CFS": ".grb2",
    },
    "config_vars_for_mapping": [
        "input_forcings",
        "input_force_dirs",
        "input_force_types",
        "input_force_mandatory",
        "fcst_input_horizons",
        "fcst_input_offsets",
        "ignored_border_widths",
        "regrid_opt",
        "dScaleParamDirs",
        "forceTemoralInterp",
        "t2dDownscaleOpt",
        "swDownscaleOpt",
        "psfcDownscaleOpt",
        "precipDownscaleOpt",
        "q2dDownscaleOpt",
        "t2BiasCorrectOpt",
        "psfcBiasCorrectOpt",
        "q2BiasCorrectOpt",
        "windBiasCorrect",
        "swBiasCorrectOpt",
        "lwBiasCorrectOpt",
        "precipBiasCorrectOpt",
    ],
}
TEST_UTILS = {
    "OLD_NEW_VAR_MAP": {
        "q2dBiasCorrectOpt": "q2BiasCorrectOpt",
        "paramDir": "dScaleParamDirs",
        "border": "ignored_border_widths",
        "regridOpt": "regrid_opt",
        "userFcstHorizon": "fcst_input_horizons",
        "inDir": "input_force_dirs",
        "swDowscaleOpt": "swDownscaleOpt",
        "t2dBiasCorrectOpt": "t2BiasCorrectOpt",
        "userCycleOffset": "fcst_input_offsets",
        "windBiasCorrectOpt": "windBiasCorrect",
        "timeInterpOpt": "forceTemoralInterp",
        "enforce": "input_force_mandatory",
        "file_type": "input_force_types",
    }
}
FORCING_EXTRACTION = {
    # Set mapping between InputForcings codes and forcing extraction scripts
    "forcing_src": {
        3: "Global/get_prod_GFS.py",
        5: "CONUS/get_conus_HRRR.py",
        6: "CONUS/get_conus_RAP.py",
        7: "Global/get_CFSv2.py",
        13: "Hawaii/get_prod_NAM_Nest_Hawaii.py",
        14: "Puerto_Rico/get_prod_NAM_Nest_Puerto_Rico.py",
        19: "Alaska/get_Alaska_HRRR.py",
        24: "CONUS/get_prod_NBM_Conus.py",
        "supp8": "CONUS/get_prod_NBM_Conus.py",
        "supp9": "Alaska/get_prod_NBM_Alaska.py",
        "supp11": "Alaska/get_Alaska_StageIV.py",
        "supp12": "CONUS/get_conus_StageIV.py",
        "supp15": "Puerto_Rico/get_prod_NBM_Puerto_Rico.py",
        "supp16": "Hawaii/get_prod_NBM_Hawaii.py",
    },
    # Set mapping between InputForcings codes and forcing extraction scripts
    "forcing_ana_src": {
        5: "CONUS/get_conus_HRRR_AnA.py",
        6: "CONUS/get_conus_RAP_AnA.py",
        13: "Hawaii/get_prod_NAM_Nest_Hawaii.py",
        14: "Puerto_Rico/get_prod_NAM_Nest_Puerto_Rico_AnA.py",
        19: "Alaska/get_Alaska_HRRR.py",
        20: "Alaska/get_Alaska_HRRR_AnA.py",
        "supp1": "CONUS/get_conus_MRMS_Radar.py",
        "supp2": "CONUS/get_conus_MRMS_MultiSensor.py",
        "supp6": "Hawaii/get_MRMS_MultiSensor_Hawaii.py",
        "supp10": "Alaska/get_MRMS_MultiSensor_Alaska.py",
        "supp11": "Alaska/get_Alaska_StageIV.py",
        "supp12": "CONUS/get_conus_StageIV.py",
        "supp15": "Puerto_Rico/get_prod_NBM_Puerto_Rico_AnA.py",
    },
    "extraction_script_path": "/ngen-app/ngen-forcing/Forcing_Extraction_Scripts",
}
GEOMOD = {
    "GeoMeta": [
        "nodeCoords",
        "centerCoords",
        "inds",
        "esmf_lat",
        "esmf_lon",
    ],
    "UnstructuredGeoMeta": [
        "x_lower_bound",
        "x_upper_bound",
        "y_lower_bound",
        "y_upper_bound",
        "dx_meters",
        "dy_meters",
        "element_ids",
        "element_ids_global",
        "sina_grid",
        "cosa_grid",
        "esmf_lat",
        "esmf_lon",
    ],
    "HydrofabricGeoMeta": [
        "nx_local_elem",
        "ny_local_elem",
        "x_lower_bound",
        "x_upper_bound",
        "y_lower_bound",
        "y_upper_bound",
        "nx_global_elem",
        "ny_global_elem",
        "dx_meters",
        "dy_meters",
        "mesh_inds_elem",
        "height_elem",
        "sina_grid",
        "cosa_grid",
        "slope_elem",
        "slp_azi_elem",
        "esmf_lat",
        "esmf_lon",
        "latitude_grid_elem",
        "longitude_grid_elem",
    ],
    "GriddedGeoMeta": [
        "nx_local_elem",
        "ny_local_elem",
        "nx_global_elem",
        "ny_global_elem",
        "element_ids",
        "element_ids_global",
        "lat_bounds",
        "lon_bounds",
        "mesh_inds",
        "mesh_inds_elem",
        "height_elem",
        "slope_elem",
        "slp_azi_elem",
        "latitude_grid_elem",
        "longitude_grid_elem",
    ],
}

FORCINGINPUTMOD = {
    "InputForcings": [
        "nx_global",
        "ny_global",
        "nx_local",
        "ny_local",
        "nx_local_corner",
        "ny_local_corner",
        "x_lower_bound",
        "x_upper_bound",
        "y_lower_bound",
        "y_upper_bound",
        "x_lower_bound_corner",
        "x_upper_bound_corner",
        "y_lower_bound_corner",
        "y_upper_bound_corner",
        "outFreq",
        "lapseGrid",
        "rqiClimoGrid",
        "nwmPRISM_numGrid",
        "nwmPRISM_denGrid",
        "esmf_lats",
        "esmf_lons",
        "esmf_grid_in",
        "esmf_grid_in_elem",
        "regridObj",
        "regridObj_elem",
        "esmf_field_in",
        "esmf_field_in_elem",
        "esmf_field_out",
        "esmf_field_out_elem",
        # --------------------------------
        # Only used for CFSv2 bias correction
        # as bias correction needs to take
        # place prior to regridding.
        "coarse_input_forcings1",
        "coarse_input_forcings2",
        # --------------------------------
        "regridded_forcings1",
        "regridded_forcings2",
        "globalPcpRate1",
        "globalPcpRate2",
        "regridded_forcings1_elem",
        "regridded_forcings2_elem",
        "globalPcpRate1_elem",
        "globalPcpRate2_elem",
        "ndv",
        "file_in1",
        "file_in2",
        "fcst_hour1",
        "fcst_hour2",
        "fcst_date1",
        "fcst_date2",
        "tmpFile",
        "tmpFileHeight",
        "regridded_precip1",
        "regridded_precip2",
        "regridded_precip1_elem",
        "regridded_precip2_elem",
        "_grib_vars",
        "_cycle_freq",
        "_t2dTmp",
        "_psfcTmp",
        "_final_forcings",
        "_height",
        "_regridded_mask",
        "_regridded_mask_AORC",
    ],
    "InputForcingsGridded": [
        "t2dTmp_elem",
        "psfcTmp_elem",
        "final_forcings_elem",
        "height_elem",
        "regridded_mask_elem",
        "regridded_mask_elem_AORC",
    ],
    "InputForcingsHydrofabric": [
        "final_forcings_elem",
        "height_elem",
        "regridded_mask_elem",
        "regridded_mask_elem_AORC",
        "t2dTmp_elem",
        "psfcTmp_elem",
    ],
    "InputForcingsUnstructured": [
        "_t2dTmp_elem",
        "_psfcTmp_elem",
        "_final_forcings_elem",
        "_height_elem",
        "_regridded_mask_elem",
        "_regridded_mask_elem_AORC",
    ],
    "PRODUCT_NAME": {
        1: "NLDAS2_GRIB1",
        2: "NARR_GRIB1",
        3: "GFS_Production_GRIB2",
        4: "NAM_Conus_Nest_GRIB2",
        5: "HRRR_Conus_GRIB2",
        6: "RAP_Conus_GRIB2",
        7: "CFSv2_6Hr_Global_GRIB2",
        8: "WRF_ARW_Hawaii_GRIB2",
        9: "GFS_Production_025d_GRIB2",
        10: "Custom_NetCDF_Hourly",
        11: "Custom_NetCDF_Hourly",
        12: "AORC",
        13: "NAM_Nest_3km_Hawaii",
        14: "NAM_Nest_3km_PuertoRico",
        15: "NAM_Nest_3km_Alaska",
        16: "NAM_Nest_3km_Hawaii_Radiation-Only",
        17: "NAM_Nest_3km_PuertoRico_Radiation-Only",
        18: "WRF_ARW_PuertoRico_GRIB2",
        19: "HRRR_Alaska_GRIB2",
        20: "Alaska_AnA",
        21: "AORC_Alaska",
        22: "Alaska_ExtAnA",
        23: "ERA5",
        24: "NBM",
        25: "NDFD",
        26: "HRRR_15min",
        27: "NWM",
    },
    "CYCLE_FREQ": {
        1: 60,
        2: 180,
        3: 360,
        4: 360,
        5: 60,
        6: 60,
        7: 360,
        8: 1440,
        9: 360,
        10: -9999,
        11: -9999,
        12: -9999,
        13: 360,
        14: 360,
        15: 360,
        16: 360,
        17: 360,
        18: 1440,
        19: 180,
        20: 180,
        21: -9999,
        22: 180,
        23: -9999,
        24: 60,
        25: 1440,
        26: 15,
        27: -9999,
    },
    "GRIB_VARS": {
        1: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        2: None,
        3: [
            "TMP",
            "SPFH",
            "UGRD",
            "VGRD",
            "PRATE",
            "DSWRF",
            "DLWRF",
            "PRES",
            "CPOFP",
        ],
        4: None,
        5: [
            "TMP",
            "SPFH",
            "UGRD",
            "VGRD",
            "APCP",
            "DSWRF",
            "DLWRF",
            "PRES",
            "CPOFP",
        ],
        6: [
            "TMP",
            "SPFH",
            "UGRD",
            "VGRD",
            "APCP",
            "DSWRF",
            "DLWRF",
            "PRES",
            "FROZR",
        ],
        7: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        8: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "PRES"],
        9: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        10: None,
        11: None,
        12: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        13: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        14: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        15: ["TMP", "SPFH", "UGRD", "VGRD", "PRATE", "DSWRF", "DLWRF", "PRES"],
        16: ["DSWRF", "DLWRF"],
        17: ["DSWRF", "DLWRF"],
        18: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "PRES"],
        19: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        20: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        21: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        22: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        23: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        24: ["TMP", "APCP"],
        25: ["TMP", "WDIR", "WSPD", "APCP"],
        26: ["TMP", "SPFH", "UGRD", "VGRD", "APCP", "DSWRF", "DLWRF", "PRES"],
        27: [
            "T2D",
            "Q2D",
            "U2D",
            "V2D",
            "RAINRATE",
            "SWDOWN",
            "LWDOWN",
            "PSFC",
        ],
    },
    "GRIB_LEVELS": {
        1: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        2: None,
        3: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        4: None,
        5: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        6: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        7: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        8: [
            "80 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
        ],
        9: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        10: None,
        11: None,
        12: None,
        13: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        14: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        15: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        16: ["surface", "surface"],
        17: ["surface", "surface"],
        18: [
            "80 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
        ],
        19: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        20: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        21: None,
        22: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        23: None,
        24: ["2 m above ground", "surface"],
        25: [
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
        ],
        26: [
            "2 m above ground",
            "2 m above ground",
            "10 m above ground",
            "10 m above ground",
            "surface",
            "surface",
            "surface",
            "surface",
        ],
        27: None,
    },
    "NET_CDF_VARS_NAMES": {
        1: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        2: None,
        3: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
            "CPOFP_surface",
        ],
        4: None,
        5: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
            "CPOFP_surface",
        ],
        6: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
            "FROZR_surface",
        ],
        7: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        8: [
            "TMP_80maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "PRES_surface",
        ],
        9: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        10: ["T2D", "Q2D", "U10", "V10", "RAINRATE", "DSWRF", "DLWRF", "PRES"],
        11: ["T2D", "Q2D", "U10", "V10", "RAINRATE", "DSWRF", "DLWRF", "PRES"],
        12: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        13: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        14: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        15: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "PRATE_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        16: ["DSWRF_surface", "DLWRF_surface"],
        17: ["DSWRF_surface", "DLWRF_surface"],
        18: [
            "TMP_80maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "PRES_surface",
        ],
        19: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        20: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        21: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        22: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        23: ["t2m", "d2m", "u10", "v10", "mtpr", "msdwswrf", "msdwlwrf", "sp"],
        24: ["TMP_2maboveground", "APCP_surface"],
        25: [
            "TMP_2maboveground",
            "WDIR_10maboveground",
            "WIND_10maboveground",
            "APCP_surface",
        ],
        26: [
            "TMP_2maboveground",
            "SPFH_2maboveground",
            "UGRD_10maboveground",
            "VGRD_10maboveground",
            "APCP_surface",
            "DSWRF_surface",
            "DLWRF_surface",
            "PRES_surface",
        ],
        27: ["T2D", "Q2D", "U2D", "V2D", "RAINRATE", "SWDOWN", "LWDOWN", "PSFC"],
    },
    "GRIB_MES_IDX": {
        1: None,
        2: None,
        3: None,
        4: None,
        5: None,
        6: None,
        7: None,
        8: None,
        9: [33, 34, 39, 40, 43, 88, 91, 6],
        10: None,
        11: None,
        12: None,
        13: None,
        14: None,
        15: None,
        16: None,
        17: None,
        18: None,
        19: None,
        20: None,
        21: None,
        22: None,
        23: None,
        24: None,
        25: None,
        26: None,
        27: None,
    },
    "INPUT_MAP_OUTPUT": {
        1: [4, 5, 0, 1, 3, 7, 2, 6],
        2: None,
        3: [4, 5, 0, 1, 3, 7, 2, 6, 8],
        4: None,
        5: [4, 5, 0, 1, 3, 7, 2, 6, 8],
        6: [4, 5, 0, 1, 3, 7, 2, 6, 8],
        7: [4, 5, 0, 1, 3, 7, 2, 6],
        8: [4, 5, 0, 1, 3, 6],
        9: [4, 5, 0, 1, 3, 7, 2, 6],
        10: [4, 5, 0, 1, 3, 7, 2, 6],
        11: [4, 5, 0, 1, 3, 7, 2, 6],
        12: [4, 5, 0, 1, 3, 7, 2, 6],
        13: [4, 5, 0, 1, 3, 7, 2, 6],
        14: [4, 5, 0, 1, 3, 7, 2, 6],
        15: [4, 5, 0, 1, 3, 7, 2, 6],
        16: [7, 2],
        17: [7, 2],
        18: [4, 5, 0, 1, 3, 6],
        19: [4, 5, 0, 1, 3, 7, 2, 6],
        20: [4, 5, 0, 1, 3, 7, 2, 6],
        21: [4, 5, 0, 1, 3, 7, 2, 6],
        22: [4, 5, 0, 1, 3, 7, 2, 6],
        23: [4, 5, 0, 1, 3, 7, 2, 6],
        24: [4, 3],
        25: [4, 0, 1, 3],
        26: [4, 5, 0, 1, 3, 7, 2, 6],
        27: [4, 5, 0, 1, 3, 7, 2, 6],
    },
    "FORECAST_HORIZONS": {
        1: None,
        2: None,
        3: None,
        4: None,
        5: [
            18,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
        ],
        6: [
            21,
            21,
            21,
            39,
            21,
            21,
            21,
            21,
            21,
            39,
            21,
            21,
            21,
            21,
            21,
            39,
            21,
            21,
            21,
            21,
            21,
            39,
            21,
            21,
        ],
        7: None,
        8: None,
        9: None,
        10: None,
        11: None,
        12: None,
        13: None,
        14: None,
        15: None,
        16: None,
        17: None,
        18: None,
        19: None,
        20: None,
        21: None,
        22: None,
        23: None,
        24: None,
        25: None,
        26: [
            18,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
            36,
            18,
            18,
            18,
            18,
            18,
        ],
        27: None,
    },
    "FIND_NEIGHBOR_FILES_MAP": {
        1: time_handling.find_nldas_neighbors,
        3: time_handling.find_gfs_neighbors,
        5: time_handling.find_conus_hrrr_neighbors,
        6: time_handling.find_conus_rap_neighbors,
        7: time_handling.find_cfsv2_neighbors,
        8: time_handling.find_hourly_wrf_arw_neighbors,
        9: time_handling.find_gfs_neighbors,
        10: time_handling.find_custom_hourly_neighbors,
        11: time_handling.find_custom_hourly_neighbors,
        12: time_handling.find_aorc_neighbors,
        13: time_handling.find_nam_nest_neighbors,
        14: time_handling.find_nam_nest_neighbors,
        15: time_handling.find_nam_nest_neighbors,
        16: time_handling.find_nam_nest_neighbors,
        17: time_handling.find_nam_nest_neighbors,
        18: time_handling.find_hourly_wrf_arw_neighbors,
        19: time_handling.find_ak_hrrr_neighbors,
        20: time_handling.find_ak_hrrr_neighbors,
        21: time_handling.find_aorc_neighbors,
        22: time_handling.find_ak_hrrr_neighbors,
        23: time_handling.find_era5_neighbors,
        24: time_handling.find_hourly_nbm_neighbors,
        25: time_handling.find_ndfd_neighbors,
        26: time_handling.find_input_neighbors,
        27: time_handling.find_nwm_neighbors,
    },
    "REGRID_MAP": {
        1: regrid.regrid_conus_rap,
        3: regrid.regrid_gfs,
        5: regrid.regrid_conus_hrrr,
        6: regrid.regrid_conus_rap,
        7: regrid.regrid_cfsv2,
        8: regrid.regrid_hourly_wrf_arw,
        9: regrid.regrid_gfs,
        10: regrid.regrid_custom_hourly_netcdf,
        11: regrid.regrid_custom_hourly_netcdf,
        12: regrid.regrid_custom_hourly_netcdf,
        13: regrid.regrid_nam_nest,
        14: regrid.regrid_nam_nest,
        15: regrid.regrid_nam_nest,
        16: regrid.regrid_nam_nest,
        17: regrid.regrid_nam_nest,
        18: regrid.regrid_hourly_wrf_arw,
        19: regrid.regrid_conus_hrrr,
        20: regrid.regrid_conus_hrrr,
        21: regrid.regrid_custom_hourly_netcdf,
        22: regrid.regrid_conus_hrrr,
        23: regrid.regrid_era5,
        24: regrid.regrid_hourly_nbm,
        25: regrid.regrid_ndfd,
        26: regrid.regrid_conus_hrrr,
        27: regrid.regrid_nwm,
    },
    "TEMPORAL_INTERPOLATE_INPUTS_MAP": {
        0: no_interpolation,
        1: nearest_neighbor,
        2: weighted_average,
    },
    "FILE_EXT": {
        "GRIB1": ".grb",
        "GRIB2": ".grib2",
        "NETCDF": ".nc",
        "NETCDF4": ".nc4",
        "NWM": ".LDASIN_DOMAIN1",
        "ZARR": ".zarr",
        "GRIB2_CFS": ".grb2",
    },
    "config_vars_for_mapping": [
        "input_forcings",
        "input_force_dirs",
        "input_force_types",
        "input_force_mandatory",
        "fcst_input_horizons",
        "fcst_input_offsets",
        "ignored_border_widths",
        "regrid_opt",
        "dScaleParamDirs",
        "forceTemoralInterp",
        "t2dDownscaleOpt",
        "swDownscaleOpt",
        "psfcDownscaleOpt",
        "precipDownscaleOpt",
        "q2dDownscaleOpt",
        "t2BiasCorrectOpt",
        "psfcBiasCorrectOpt",
        "q2BiasCorrectOpt",
        "windBiasCorrect",
        "swBiasCorrectOpt",
        "lwBiasCorrectOpt",
        "precipBiasCorrectOpt",
    ],
}
TEST_UTILS = {
    "OLD_NEW_VAR_MAP": {
        "q2dBiasCorrectOpt": "q2BiasCorrectOpt",
        "paramDir": "dScaleParamDirs",
        "border": "ignored_border_widths",
        "regridOpt": "regrid_opt",
        "userFcstHorizon": "fcst_input_horizons",
        "inDir": "input_force_dirs",
        "swDowscaleOpt": "swDownscaleOpt",
        "t2dBiasCorrectOpt": "t2BiasCorrectOpt",
        "userCycleOffset": "fcst_input_offsets",
        "windBiasCorrectOpt": "windBiasCorrect",
        "timeInterpOpt": "forceTemoralInterp",
        "enforce": "input_force_mandatory",
        "file_type": "input_force_types",
    }
}
