time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "medium_range_ndfd"
InputForcings: [3, 25] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NDFD_test/GFS",'/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NDFD_test/NDFD']
InputForcingTypes: ["GRIB2","GRIB2"]
InputMandatory: [1,1]
OutputFrequency: 60
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/Medium_range"
Output: 1
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : -9999
RefcstBDateProc: "202405280000"
ForecastFrequency: 360
ForecastShift: 0
ForecastInputHorizons: [14400,14400]
ForecastInputOffsets: [0,0]
GeogridIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/geo_em_CONUS.nc"
SpatialMetaIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/GEOGRID_LDASOUT_Spatial_Metadata_CONUS.nc"
GRID_TYPE: "gridded"
LONVAR: 'XLONG_M'
LATVAR: 'XLAT_M'
HGTVAR: 'Element_Elevation'
SINALPHA: 'SINALPHA'
COSALPHA: 'COSALPHA'
HGTVAR: 'HGT_M'
IgnoredBorderWidths: [0,0]
RegridOpt: [1,2]
ForcingTemporalInterpolation: [0,0]
TemperatureBiasCorrection: [3,0]
PressureBiasCorrection: [0,0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [3,0]
SwBiasCorrection: [0,0]
LwBiasCorrection: [3,0]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [2,0]
ShortwaveDownscaling: [1,0]
PressureDownscaling: [1,0]
PrecipDownscaling: [1,0]
HumidityDownscaling: [1,0]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Medium_Range","./NWM_Params"]
SuppPcp: []
SuppPcpForcingTypes: ''
SuppPcpDirectories: ''
SuppPcpParamDir: ''
RegridOptSuppPcp: []
SuppPcpTemporalInterpolation: []
SuppPcpInputOffsets: []
SuppPcpMandatory: []
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFrac: 1
