time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "long_range_mem1"
InputForcings: [7] 
InputForcingDirectories: ["{root_dir}/raw_input/CFS"]
InputForcingTypes: ["GRIB2"]
InputMandatory: [1]
OutputFrequency: 360
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "{root_dir}/scratch/long_range/"
Output: 0
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : -9999
RefcstBDateProc: "202410280000"
ForecastFrequency: 360
ForecastShift: 0
ForecastInputHorizons: [43200]
ForecastInputOffsets: [0]
Geopackage: "{root_dir}/gpkg/conus/{gage}.gpkg"
GeogridIn: "{root_dir}/esmf_mesh/{gage}_ESMF_Mesh.nc"
SpatialMetaIn: ""
GRID_TYPE: "hydrofabric"
NodeCoords: 'nodeCoords'
ElemCoords: 'centerCoords'
ElemConn: 'elementConn'
ElemID: 'element_id'
NumElemConn: 'numElementConn'
HGTVAR: 'Element_Elevation'
SLOPE: 'Element_Slope'
SLOPE_AZIMUTH: 'Element_Slope_Azmuith'
IgnoredBorderWidths: [0]
RegridOpt: [1]
ForcingTemporalInterpolation: [0]
TemperatureBiasCorrection: [0]
PressureBiasCorrection: [0]
HumidityBiasCorrection: [0]
WindBiasCorrection: [0]
SwBiasCorrection: [0]
LwBiasCorrection: [0]
PrecipBiasCorrection: [0]
TemperatureDownscaling: [0]
ShortwaveDownscaling: [0]
PressureDownscaling: [0]
PrecipDownscaling: [0]
HumidityDownscaling: [0]
DownscalingParamDirs: ["{root_dir}"]
SuppPcp: []
SuppPcpForcingTypes: []
SuppPcpDirectories: []
SuppPcpParamDir: ''
RegridOptSuppPcp: []
SuppPcpTemporalInterpolation: []
SuppPcpInputOffsets: []
SuppPcpMandatory: []
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: 1
custom_input_fcst_freq: []
includeLQFrac: 1
