time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "short_range"
InputForcings: [16,8]
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NAM_Nest_Hawaii", "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/WRF_ARW_Hawaii"]
InputForcingTypes: ["GRIB2", "GRIB2"]
InputMandatory: [1,1]
OutputFrequency: 60
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/Short_range"
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : -9999
RefcstBDateProc: "202309250000"
ForecastFrequency: 720
ForecastShift: 0
ForecastInputHorizons: [2880, 2880]
ForecastInputOffsets: [0, 0]
GeogridIn: "./NextGen_Domains/unstructured/SCHISM_Alaska_ESMF_Mesh.nc"
SpatialMetaIn: ""
GRID_TYPE: "unstructured"
NodeCoords: 'nodeCoords'
ElemCoords: 'centerCoords'
ElemConn: 'elementConn'
NumElemConn: 'numElementConn'
HGTVAR: 'Node_Elevations'
HGTVAR_ELEM: 'Element_Elevations'
IgnoredBorderWidths: [0, 0]
RegridOpt: [1, 1]
ForcingTemporalInterpolation: [0, 0]
TemperatureBiasCorrection: [0, 0]
PressureBiasCorrection: [0, 0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [0,0]
SwBiasCorrection: [0,0]
LwBiasCorrection: [0,0]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [0,0]
ShortwaveDownscaling: [0,0]
PressureDownscaling: [0,0]
PrecipDownscaling: [0,0]
HumidityDownscaling: [0,0]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Hawaii", "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Hawaii"]
SuppPcp: []
SuppPcpForcingTypes: []
SuppPcpDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/WRF_ARW_Hawaii"]
SuppPcpParamDir: '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Hawaii'
RegridOptSuppPcp: [1]
SuppPcpTemporalInterpolation: [0]
SuppPcpInputOffsets: [0]
SuppPcpMandatory: [0]
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: '1'
custom_input_fcst_freq: []
includeLQFrac: 0
