#/usr/bin/evn bash

set -x

#--------------------------------------------------------------
#This task runs the coastal forcing engine, which creates coastal forcing data using LDASIN files found in:
#
#   ${forcing_atm} e.g. $GESIN/analysis_assim
#
#using the geogrid file at:
#
#  $PARMnwm/domain_$NWM_DOMAIN/$GEOGRID_FILE
#
#for $LENGTH_HRS hours beginning at $CYCLE_DATE $CYCLE_TIME (or ending at this time, if using a negative lookback).
#
#Coastal orcing output (vsource.th.2, source_sink.in.2, msource.th.2) is written to:
#
#   $COASTAL_FORCING_OUTPUT_DIR, e.g.  ${GESOUT}/${CASETYPE}
#
#and symlinked to:
#
#   $DATAexec
#
post_nwm_forcing_coastal() {

  PDY=${1:0:8}
  cyc=${1:8}
  export COASTAL_FORCING_OUTPUT_DIR=$2
  export LENGTH_HRS=$3
  nwm_forcing_retro_dir=$4

  local _file;

  export FORCING_BEGIN_DATE=${PDY}${cyc}00
  export NWM_FORCING_OUTPUT_DIR=$DATAexec/forcing_input
  export FORCING_END_DATE=$(${USHnwm}/utils/advance_time.sh $PDY$cyc $LENGTH_HRS)'00'
  export COASTAL_FORCING_INPUT_DIR=$NWM_FORCING_OUTPUT_DIR/${FORCING_BEGIN_DATE:0:10}
  export COASTAL_WORK_DIR=$DATAexec
  export FORCING_START_YEAR=${PDY:0:4}
  export FORCING_START_MONTH=${PDY:4:2}
  export FORCING_START_DAY=${PDY:6:2}
  export FORCING_START_HOUR=${cyc}

  # symlink SCHISM forcing inputs generated by FECPP
  #ln -sf $COASTAL_FORCING_OUTPUT_DIR/vsource.th.2 $COASTAL_FORCING_OUTPUT_DIR/source_sink.in.2 $COASTAL_FORCING_OUTPUT_DIR/msource.th.2 $DATAexec
  ln -sf $COASTAL_FORCING_OUTPUT_DIR/precip_source.nc $DATAexec

  # call makeAtmo to generate final inputs
  # TODO: output this format directly from FECPP

  mkdir -p $DATAexec/sflux/

  python -u $USHnwm/wrf_hydro_workflow_dev/coastal/makeAtmo.py >> $DATAlogs/nwm_forcing_${PDY}${cyc}.log 2>&1

}
