name: NextGen_lumped_forcings_driver
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - xarray
  - dask
  - pandas
  - python
  - netCDF4
  - pybind11
  - geopandas
  - gdal
  - numpy
  - wget
  - pathlib
  - shapely
  - scipy
  - pyarrow
  - multiprocess
  - regex
  - openssl
